# This config file is used by ros2_control
/**:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz
      # is_async: true
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
      
  imu_sensor_broadcaster:
    ros__parameters:
      update_rate: 100  # Hz
      sensor_name: imu
      frame_id:  imu
  joint_state_broadcaster:
    ros__parameters:
      update_rate: 100  # Hz
